gesdinet_jwt_refresh_token:
    ttl: 2592000
    # cookie:
    #   enabled: true
    #   same_site: lax               # default value
    #   path: /                      # default value
    #   domain: null                 # default value
    #   http_only: true              # default value
    #   secure: false                # default value
